### ISSUE TITLE
Create CSV file in better way

### ISSUE THREAD

**Issue by Web-Cam** [Web-Cam/WebScraper#10]
Currently CSV file is created by hand, making it hard to include additional fields 

`        mapdata.write('"' + businessName + '",' + '"' + location + '",' + '"' + address +'","' + phoneNumber + '","' + website + '"\n')  # format proper
`

Find better way to create the CSV file possibly using pandas

**Comment by Alexander-Alvarado** [comment]
pull #22 addresses this issue
