### ISSUE TITLE
Fix number of employees formatting

### ISSUE THREAD

**Issue by Alexander-Alvarado** [Web-Cam/WebScraper#17]
The number of employees information comes from crunchbase and certain values are interpenetrated as dates 
Example:

![image](https://user-images.githubusercontent.com/55999674/73600143-5540d580-451a-11ea-9ce1-b84b21cd8fed.png)

turns to 

![image](https://user-images.githubusercontent.com/55999674/73600162-83beb080-451a-11ea-8b09-6263e5a7a1bd.png)

Add a check to the formatting to keep the number of employees a range of numbers

**Comment by Web-Cam** [comment]
![image](https://user-images.githubusercontent.com/32422075/73601496-c68b8300-4530-11ea-966d-8bd9ca5ee8b2.png)
Should be a problem in excel formatting only, there may be a setting in excel to change it

**Comment by Alexander-Alvarado** [comment]
This is not an issue with excel, the problem is in the raw CSV values. You can open the crunch_bases_view.csv file in note pad to see that this is an issue with the data.

Examples:
![image](https://user-images.githubusercontent.com/55999674/73601571-f25b3880-4531-11ea-9c82-050b7b3fa974.png)
![image](https://user-images.githubusercontent.com/55999674/73601576-fd15cd80-4531-11ea-9489-ad510e6b5aa9.png)
![image](https://user-images.githubusercontent.com/55999674/73601585-1cacf600-4532-11ea-9c02-54a44e4ebad0.png)

**Comment by Alexander-Alvarado** [comment]
this appears to actually be an issue with excel overwriting the csv file and forcing its formatting.
