### ISSUE TITLE
Fix formatting of businesses 

### ISSUE THREAD

**Issue by Web-Cam** [Web-Cam/WebScraper#20]
Appears that formatting is wrong on a few companies, leading to an extra quotation mark.
![image](https://user-images.githubusercontent.com/32422075/73696671-c0b9ad00-46aa-11ea-934f-e91b0115867b.png)

**Comment by Alexander-Alvarado** [comment]
pull #21 addressed this issue

![image](https://user-images.githubusercontent.com/55999674/73707771-747e6500-46ca-11ea-8a83-c33c6e3d1c58.png)
