### ISSUE TITLE
Extra comma in end of CSV rows 

### ISSUE THREAD

**Issue by Web-Cam** [Web-Cam/WebScraper#26]
![image](https://user-images.githubusercontent.com/32422075/73796587-997ee080-477b-11ea-8f27-484b091dd419.png)
Some entires have an extra comma at end of CSV file
![image](https://user-images.githubusercontent.com/32422075/73796621-b2879180-477b-11ea-946f-6334de4c42ef.png)

**Comment by Alexander-Alvarado** [comment]
pull #27 addresses this issue
