### ISSUE TITLE
Dynamically get names and count of rows

### ISSUE THREAD

**Issue by Web-Cam** [Web-Cam/WebScraper#3]
Instead of having row names in a array, get them form the file automatically. 

`
 names = ['id','created_at','updated_at',ETC...]
 col_Count = 26
 `

**Comment by Alexander-Alvarado** [comment]
Assign to me

**Comment by Alexander-Alvarado** [comment]
solved with [pull request #12](https://github.com/Web-Cam/WebScraper/pull/12), mark as closed
