### ISSUE TITLE
maps api returning wrong infromation

### ISSUE THREAD

**Issue by Alexander-Alvarado** [Web-Cam/WebScraper#30]
there are instances where the maps api will return incorrect information.

example:
![image](https://user-images.githubusercontent.com/55999674/73807708-60eeff00-479b-11ea-8df5-41d4bc3868fe.png)

the address, phone number, and website for this row is for a different company. google maps shows that 12th Avenue Graphics is permanently closed, and the api most likely does not return information on businesses that have closed down.

**Comment by Web-Cam** [comment]
Interesting, ran it again and it appeared to work

![image](https://user-images.githubusercontent.com/32422075/73865033-a00b6780-4810-11ea-9d44-7f566fa0f0a7.png)

Possibly some weird case?

**Comment by Alexander-Alvarado** [comment]
this appears to have been a one time error, will reopen if the problem persists
