### ISSUE TITLE
mapdata written over

### ISSUE THREAD

**Issue by Web-Cam** [Web-Cam/WebScraper#41]
mapdata.csv is written over with a new file, instead of appending when a company has been scanned in the last 30 days. 
![image](https://user-images.githubusercontent.com/32422075/74990353-13b49380-5411-11ea-91f6-96524f018db2.png)
 

Ex. this should instead start with the company Cramer, Johnson, Wiggins & Associates (CJW & Associates)

**Comment by Alexander-Alvarado** [comment]
Not able to reproduce
